controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\helpers\Url;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\SignupForm;
use app\models\ContactForm;
use yii\web\UploadedFile;

use app\modules\photo\models\Photo;
use app\modules\photo\models\PhotoCategories;

class SiteController extends Controller {
    
    public function init() {
        parent::init();
        $this->layout = "site";
    }

    public function behaviors() {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    public function actions() {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function actionIndex() {
        $items = array();
        if ($photos = Photo::getAll()) {
            foreach ($photos as $photo) {
                $items[] = [
                    'url' => $photo->getUploadUrl('file'),
                    'src' => $photo->getThumbUploadUrl('file', 'preview'),
                    'options' => array('title' => $photo->title, "data-description" => "This is description"),
                ];
            }
        }
        
        $categories = array();
        if ($categories_list = PhotoCategories::getAll()) {
            foreach ($categories_list as $category) {
                $categories[] = [
                    'title' => $category->title,
                    'url' => Url::to(["category", "id" => $category->id]),
                    'src' => $category->icon
                ];
            }
        }
//        $categories[] = [
//            'title' => $category->title,
//            'url' => Url::to(["add-category", "id" => $category->id]),
//            'src' => $category->icon
//        ];
        return $this->render('index', ["items" => $items, "categories" => $categories]);
    }

    public function actionLogin() {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    public function actionLogout() {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    public function actionContact() {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

//    public function actionAbout() {
//        return $this->render('about');
//    }
    
    public function actionCategory($id = false) {
        $model = $this->findCategory($id);
        
        $items = array();
        if ($photos = Photo::getAll($id)) {
            foreach ($photos as $photo) {
                $items[] = [
                    'url' => $photo->getUploadUrl('file'),
                    'src' => $photo->getThumbUploadUrl('file', 'preview'),
                    'options' => array('title' => $photo->title),
                ];
            }
        }
        
        return $this->render('category', ["items" => $items, "model" => $model]);
    }
       
    protected function findCategory($id) {
        if (($model = PhotoCategories::find()->where(["id" => $id])->one()) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
    
    protected function confirmAuth() {
        if (Yii::$app->user->isGuest) {
            return $this->redirect("login");
        }
    }
    
    public function actionAddCategory() {
        if (Yii::$app->user->isGuest) {
            return false;
        }
        $model = new PhotoCategories();
        $model->id_user = Yii::$app->user->id;
        $model->is_show = 1;
        $model->date_created = date("Y-m-d G:i:s", time());

        if ($model->load(Yii::$app->request->post())) {
            $model->save();
        } 
        return true;
    }
    
    public function actionEditCategory($id = false) {
        $this->confirmAuth();
        
        if (!empty($id)) {
            $model = $this->findCategory($id);
        } else $model = new PhotoCategories;
        
        $model->id_user = Yii::$app->user->id;
        $model->is_show = 1;
        $model->date_created = date("Y-m-d G:i:s", time());

        if ($model->load(Yii::$app->request->post())) {
            if ($model->save()) {
                return true;
            } else return json_encode ($model->getErrors ());
        }
        
        return $this->renderAjax('forms/_edit_category', [
            'model' => $model,
        ]);
    }
    
    public function actionDeleteCategory($id = false) {
        Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        if ($this->findCategory($id)->delete()) {
            return ["success" => 1];
        }
        else return ["success" => 0];
    }
    
    public function actionUpload($id = false) {
        if (!($category = $this->findCategory($id))) {
            $this->redirect("index");
        }
        $model = new Photo();
        $model->scenario = "insert";
        $model->id_user = Yii::$app->user->id;
        $model->date_create = date("Y-m-d G:i:s", time());
        $model->id_category = $category->id;
        $model->is_active = 1;
        
        if ($model->load(Yii::$app->request->post())) {
            if ($model->_files = UploadedFile::getInstances($model, '_files')) {
                $model->file = array_shift($model->_files);
            }
                
            if ($model->save()) {
                $photos = [$model];
                if (!empty($model->_files)) {
                    foreach ($model->_files as $file) {
                        if ($file instanceof UploadedFile) {
                            $photo = new Photo(); 
                            $photo->setAttributes($model->attributes);
                            $photo->scenario = "insert";
                            $photo->file = $file;
                            $photo->title = "";
                            //Yii::$app->debug->show($photo);
                            if ($photo->validate()) {
                                if ($photo->save()) {
                                    $photos[] = $photo;
                                }
                            }
                        }
                    }
                }
                if (count($photos) > 1) {
                    return $this->render('update_all', ['models' => $photos, "category" => $id]);
                }
                else return $this->redirect(['category', 'id' => $id]);
            }
            //else Yii::$app->debug->show($model);
                
        } 
            
        return $this->render('upload', [
            'model' => $model,
            "category" => $category,
        ]);
    }
    
    public function actionSignup() {
        $model = new SignupForm();
        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->signup()) {
                if (Yii::$app->getUser()->login($user)) {
                    return $this->redirect("index");
                }
            }
        }
        
        return $this->render('signup', [
            'model' => $model,
        ]);
    }

}

views/site/_modal.php
<?php
use yii\bootstrap\Modal;
use yii\widgets\Pjax;
use yii\web\JsExpression;

use app\modules\photo\models\PhotoCategories;

Modal::begin([
    'id' => 'edit-category',
    'header' => '<h3 id="add-category-header"></h3>',
    'clientEvents' => [
        'show.bs.modal' => new JsExpression("function(event){
            var button = $(event.relatedTarget);
            var title = button.data('title');
            $(this).find('#photocategories-title').val(title);
        }"),
    ]
]);


$this->registerJs(
   '$("document").ready(function(){ 
        $("#_edit_category").on("pjax:end", function() {
            $("#edit-category").modal("hide");
            $.pjax.reload({container:"#_view_categories"});
        });
    });'
);


Pjax::begin(['id' => '_edit_category', 'enablePushState' => false]);
echo $this->render("forms/_edit_category", ["model" => new PhotoCategories]);
Pjax::end();
Modal::end();

?>

views/site/_modal_button.php
<?php
use yii\bootstrap\Modal;
use yii\widgets\Pjax;
use yii\web\JsExpression;

$modal = Modal::begin ([
    'header' => false,
    'toggleButton' => [
        'tag' => 'button',
        'rel-url' => $button['url'],
        //'rel-params' => isset($param)?json_encode($param):false,
        'label' => "<span>{$button['name']}</span>",
        "class" => $button['class'],
    ],

]);

$pjax = Pjax::begin(['enablePushState' => false]);

Pjax::end();

$this->registerJs(
   '$("document").ready(function(){ 
        $("'.$pjax->getId().'").on("pjax:end", function() {
            $("'.$modal->getId().'").modal("hide");
            $.pjax.reload({container:"'.$button['reload'].'"});
        });
    });'
);

Modal::end ();
?>

views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

views/site/category.php
<?php
use yii\bootstrap\Html;
use dosamigos\gallery\Gallery;

/* @var $this yii\web\View */

$this->title = $model->title;
$this->params['breadcrumbs'][] = $this->title;

?>
<div class="site-index">
    <div classs="col-md-12">
        <div class="panel panel-info">
            <div class="panel-heading">
                <h2><?= $model->title ?></h2>
            </div>
            <div class="panel-body">
                <div class="btn-group" role="group">
                    <?= Html::a(Html::tag("span", null, ["class" => "glyphicon glyphicon-photo", "aria-hidden" => true])." ".Yii::t('client', "Upload"),["/site/upload", "id" => $model->id], ["class" => "btn btn-success"]) ?>    
                </div>
            </div>
            <div class="panel-footer">
                <?= Gallery::widget(['items' => $items]); ?>
            </div>
        </div>
    </div>
</div>

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = Yii::t('client', 'Contact');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            <?= Yii::t('client', 'Thank you for contacting us. We will respond to you as soon as possible.'); ?>
        </div>

    <?php else: ?>

        <p>
            <?= Yii::t('client', 'If you have business inquiries or other questions, please fill out the following form to contact us. Thank you.'); ?>
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textArea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton(Yii::t('client', 'Submit'), ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        <?= Yii::t('client', 'The above error occurred while the Web server was processing your request.'); ?>
    </p>
    <p>
        <?= Yii::t('client', 'Please contact us if you think this is a server error. Thank you.'); ?>
    </p>

</div>

views/site/index.php
<?php
use yii\helpers\Url;
use yii\bootstrap\Html;
use yii\widgets\Pjax;
use app\components\ptGallery;
use \dosamigos\gallery\Carousel;

use yii\bootstrap\Modal;

use app\modules\photo\models\PhotoCategories;

/* @var $this yii\web\View */

$this->title = Yii::t('client', 'Dinamic Photos');


?>
<div class="site-index">
    
    <div classs="col-md-12">
        <div class="panel panel-info">
            <div class="panel-heading">
                <h3><?= Yii::t('client', 'Categories'); ?></h3>
            </div>
            <div class="panel-body">
                <div class="btn-group" role="group">
                    <?= Html::button(Html::tag("span", null, ["class" => "glyphicon glyphicon-plus", "aria-hidden" => true])." ".Yii::t('client', "Add"), ["class" => "btn btn-success", 'data' => ['toggle' => 'modal', 'target' => "#edit-category",]]) ?>    
                </div>
                <div class="btn-group" role="group">
                    <?= Html::button(Html::tag("span", null, ["class" => "glyphicon glyphicon-search", "aria-hidden" => true])." ".Yii::t('client', "Open"), ["class" => "btn btn-info controlls hidden", "onclick" => "openCategory(this)"]) ?>    
                </div>
                <div class="btn-group" role="group">
                    <?= 
                    $this->render("_modal_button", ["button" => [
                        "name" => Yii::t("client", "Rename"), 
                        "url" => Url::to("/site/edit-category"), 
                        "class" => "btn btn-info controlls ajax hidden", 
                        "reload" => "#_view_categories"]]
                    );
                    ?>
                    <?= Html::button(Html::tag("span", null, ["class" => "glyphicon glyphicon-trash", "aria-hidden" => true])." ".Yii::t('client', "Delete"), ["class" => "btn btn-danger controlls hidden", "onclick" => "deleteCategory(this)", "container" => ["update" => "#_view_categories"]]) ?>    
                </div>
            </div>
            <div class="panel-footer">
                <?php Pjax::begin(['id' => '_view_categories']); ?>
                <?= PhotoCategories::buildSlider(10); ?>
                <?php Pjax::end() ?>
            </div>
        </div>
        
        <?= $this->render("_modal", []); ?>
    </div>
    <div classs="col-md-12">
        <h3><?= Yii::t('client', 'Photos'); ?></h3>
        <?php
        echo ptGallery::widget([
            'items' => $items,
            'clientEvents' => [
                'onslide' => 'function(index, slide) {
                    console.log(slide);
                    var text = this.list[index].getAttribute("data-description"),
                    node = this.container.find(".description");
                    node.empty();
                    if (text) {
                        node[0].appendChild(document.createTextNode(text));
                    }
                }'
            ],
        ]);
        ?>
    </div>
</div>

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = Yii::t('client', 'Login');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p><?= Yii::t('client', 'Please fill out the following fields to login:'); ?></p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'options' => ['class' => 'form-horizontal'],
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

        <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <?= $form->field($model, 'rememberMe')->checkbox([
            'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
        ]) ?>

        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?= Html::submitButton(Yii::t('client', 'Login'), ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
                <?= Html::a(Yii::t('client', 'Registration'), ["signup"] , ['class' => 'btn btn-primary', 'name' => 'signup-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>
</div>

views/site/signup.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = Yii::t('client', 'Registration');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php $form = ActiveForm::begin([
        'id' => 'signup-form',
        'options' => ['class' => 'form-horizontal'],
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

    <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

    <?= $form->field($model, 'password')->passwordInput() ?>
    
    <?= $form->field($model, 'first_name')->textInput() ?>
    
    <?= $form->field($model, 'email')->textInput() ?>

    <div class="form-group">
        <div class="col-lg-offset-1 col-lg-11">
            <?= Html::submitButton(Yii::t('client', 'Submit'), ['class' => 'btn btn-primary', 'name' => 'signup-button']) ?>
        </div>
    </div>

    <?php ActiveForm::end(); ?>
</div>

views/site/upload.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;

use kartik\file\FileInput;
use kartik\select2\Select2;

use app\models\User;
use app\modules\photo\models\PhotoCategories;


/* @var $this yii\web\View */
/* @var $model app\modules\photo\models\Photo */

$this->title = Yii::t('client', 'Upload Photo');
$this->params['breadcrumbs'][] = ['label' => $category->title, 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="photo-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="photo-form">

    <?php 
    $form = ActiveForm::begin([
        'enableClientValidation' => false,
        'options' => [
            'enctype' => 'multipart/form-data',
        ],
    ]);
    ?>

    <?= $form->field($model, 'title')->textInput(['maxlength' => true]) ?>

    <?php
    echo $form->field($model, 'scenario')->hiddenInput()->label(false);
    echo $form->field($model, '_files[]')->widget(FileInput::classname(), [
        'options' => [
            'accept' => 'image/*',
            'multiple'=>true
        ],
        'pluginOptions' => [
            'showCaption' => false,
            'showRemove' => false,
            'showUpload' => false,
            'browseClass' => 'btn btn-primary btn-block',
            'browseIcon' => '<i class="glyphicon glyphicon-camera"></i> ',
            'browseLabel' =>  Yii::t('client', 'Select photos..'),
            'initialPreview'=> ($model->file)?Html::img($model->getThumbUploadUrl('file', 'thumb'), ['class' => 'img-thumbnail']):false, 
            'overwriteInitial'=>true,
        ],
        'pluginEvents' => [
            "fileclear" => "function() { jQuery('#".$model->getShortName(true)."-scenario').val('default');}",
            "fileloaded" => "function() { jQuery('#".$model->getShortName(true)."-scenario').val('update')}",
        ],
    ]);
    ?>

    <?= $form->field($model, 'description')->textInput(['maxlength' => true]) ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? Yii::t('common', 'Create') : Yii::t('common', 'Update'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

</div>